include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_types_as_parameter_names: ignore
    deprecated_member_use: ignore
    sort_child_properties_last: ignore

linter:
  rules:
    # Add or remove lint rules here
    # avoid_print: false
    # prefer_single_quotes: true
