name: first_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  camera: ^0.11.2
  path_provider: ^2.1.5
  google_ml_kit: ^0.20.0
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  carousel_slider: ^5.1.1
  provider: ^6.1.5
  http: ^1.4.0
  local_auth: ^2.3.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  hive: ^2.2.3
  firebase_core: ^3.15.1
  firebase_storage: ^12.4.9
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.3.1
  workmanager: ^0.8.0
  permission_handler: ^12.0.1
  webview_flutter: ^4.13.0
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  flutter_launcher_icons: ^0.13.1
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

localization:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  supported-locales:
    - en
    - fr
    - ur
